version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: script/install-docker.sh
      timeout: 60
      runas: root
  MiddleInstall:    
    - location: script/run-docker-image.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: script/stop-docker.sh
      timeout: 300
      runas: root