version: 0.0
os: linux
files:
  - source: / 
    destination: /project
hooks:
  BeforeInstall:
    - location: scripts/install-docker.sh
      timeout: 60
      runas: root
  MiddleInstall:    
    - location: scripts/run-docker-image.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop-docker.sh
      timeout: 300
      runas: root